name: schedule

on:
  schedule:
    - cron: "* * * * *"
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node_version }}

      - name: Run Node
        run: |
          git config --local user.email "1342671790@qq.com"
          git config --local user.name "tzcteddy"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          npm ci
          npm run build
          git add .
          git commit -m "update by github action"
          git push
